// AUTHENTIFICATION
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOAD_USER = "LOAD_USER";
export const LOGOUT = "LOGOUT";
// LOADING
export const LOADING = "LOADING";
export const LOADING_ADMIN = "LOADING_ADMIN";
export const LOADING_RESPO = "LOADING_RESPO";
// ADMIN
export const GET_RESPONSABLES = "GET_RESPONSABLES";
export const GET_RESPONSABLES_FAIL = "GET_RESPONSABLES_FAIL";
// RESPONSABLE
export const GET_RESSOURCES = "GET_RESSOURCES";
export const GET_RESSOURCES_FAIL = "GET_RESSOURCES_FAIL";
// USAGER
export const GET_ONE_RESSOURCE = "GET_ONE_RESSOURCE";
// USAGER
export const GET_TICKETS = "GET_TICKETS";
export const GET_TICKET = "GET_TICKET";
export const GET_TICKETS_FAIL = "GET_TICKETS_FAIL";
